---
title: "Wrangling historical energy use data"
author: "Jason Pither"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message = FALSE, echo = FALSE}
library(tidyverse)
library(here)
library(lubridate)
```

## Historical energy use

I now have historical data back to Jan 1, 2019. Of course the date/time information is stored in different way than described above... so let's wrangle, and merge with existing data.

```{r}
historical.data <- readr::read_csv(here::here("rawdata", "fortis_historical", "Jan_01_2019_May_31_2022_fortis.csv"), show_col_types = FALSE)
```

The date/time is stored in a strange way: "1/1/2019 12:00:00 AM"

So first we'll parse the date from time: (stackoverflow to the rescue [again](https://stackoverflow.com/questions/70429103/lubridate-hour-does-not-function-with-times-derived-from-parse-date-time))

```{r}
historical.data <- historical.data %>%
    mutate(date_time = parse_date_time(Date, orders = "%m/%d/%Y %I:%M:%S %p"),
           day = date(date_time), 
           hour = hour(date_time),
           kw_returned = NA,
           kw_consumed = `kWh delivered`) %>%
  select(day, hour, kw_returned, kw_consumed)
```

Write csv

```{r}
readr::write_csv(historical.data, here::here("outdata", "fortis_historical_data.csv"))
```


