<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="generator" content="pandoc" />

        <meta name="author" content="Jason" />
    
        <meta name="date" content="2023-09-12" />
    
    <title>House solar energy data analysis</title>

        <script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="site_libs/bootstrap-3.3.7/css/bootstrap.min.css" rel="stylesheet" />
        <script src="site_libs/bootstrap-3.3.7/js/bootstrap.min.js"></script>
        <script src="site_libs/navigation-1.1/tabsets.js"></script>
        <link href="site_libs/robobook-0.1/robobook.css" rel="stylesheet" />
        <link href="site_libs/robobook-0.1/robobook_fonts_embed.css" rel="stylesheet" />
        <script src="site_libs/robobook-0.1/robobook.js"></script>
        <script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
        <link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
        <script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
        <script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
        <link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
    
    
    
    
    <!-- tabsets -->
    <script>
      $(document).ready(function () {
	  window.buildTabsets("toc");
      });
      $(document).ready(function () {
	  $('.tabset-dropdown > .nav-tabs > li').click(function () {
	      $(this).parent().toggleClass('nav-tabs-open')
	  });
      });
    </script>

    <!-- code folding -->
    
    <!-- code download -->
    
    <!-- tabsets dropdown -->

    <style type="text/css">
      .tabset-dropdown > .nav-tabs {
	  display: inline-table;
	  max-height: 500px;
	  min-height: 44px;
	  overflow-y: auto;
	  background: white;
	  border: 1px solid #ddd;
	  border-radius: 4px;
      }
      
      .tabset-dropdown > .nav-tabs > li.active:before {
	  content: "";
	  font-family: 'Glyphicons Halflings';
	  display: inline-block;
	  padding: 10px;
	  border-right: 1px solid #ddd;
      }
      
      .tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
	  content: "&#xe258;";
	  border: none;
      }
      
      .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
	  content: "";
	  font-family: 'Glyphicons Halflings';
	  display: inline-block;
	  padding: 10px;
	  border-right: 1px solid #ddd;
      }
      
      .tabset-dropdown > .nav-tabs > li.active {
	  display: block;
      }

      .tabset-dropdown > .nav-tabs > li.active a {
  	  padding: 0 15px !important;
      }

      .tabset-dropdown > .nav-tabs > li > a,
      .tabset-dropdown > .nav-tabs > li > a:focus,
      .tabset-dropdown > .nav-tabs > li > a:hover {
	  border: none;
	  display: inline-block;
	  border-radius: 4px;
	  background-color: transparent;
      }
      
      .tabset-dropdown > .nav-tabs.nav-tabs-open > li {
	  display: block;
	  float: none;
      }
      
      .tabset-dropdown > .nav-tabs > li {
	  display: none;
	  margin-left: 0 !important;
      }
    </style>
    
</head>

<body class="preload">

   	
            <!-- robobook start -->   
   <div class="book with-summary">
      <div class="book-summary">
        <ul>
          <li class="title">House solar energy data analysis</li>
          <li class="divider"></li>
        </ul>
        <nav role="navigation" id="toc">
          <ul>
          <li><a href="#background" id="toc-background"><span class="toc-section-number">1</span> Background</a>
          <ul>
          <li><a href="#our-household" id="toc-our-household"><span class="toc-section-number">1.1</span> Our household</a></li>
          <li><a href="#household-energy-consumption" id="toc-household-energy-consumption"><span class="toc-section-number">1.2</span> Household energy consumption</a></li>
          <li><a href="#the-solar-array" id="toc-the-solar-array"><span class="toc-section-number">1.3</span> The solar array</a></li>
          <li><a href="#installation-cost" id="toc-installation-cost"><span class="toc-section-number">1.4</span> Installation cost</a></li>
          <li><a href="#electricity-supplier" id="toc-electricity-supplier"><span class="toc-section-number">1.5</span> Electricity supplier</a></li>
          </ul></li>
          <li><a href="#consumption-and-production-data" id="toc-consumption-and-production-data"><span class="toc-section-number">2</span> Consumption and Production Data</a>
          <ul>
          <li><a href="#solar-energy-production-data" id="toc-solar-energy-production-data"><span class="toc-section-number">2.1</span> Solar energy production data</a></li>
          <li><a href="#grid-energy-consumption-data" id="toc-grid-energy-consumption-data"><span class="toc-section-number">2.2</span> Grid energy consumption data</a></li>
          <li><a href="#historical-data" id="toc-historical-data"><span class="toc-section-number">2.3</span> Historical data</a></li>
          <li><a href="#average-annual-consumption-hist_consumption." id="toc-average-annual-consumption-hist_consumption."><span class="toc-section-number">2.4</span> Average annual consumption {#hist_consumption}.</a></li>
          <li><a href="#production" id="toc-production"><span class="toc-section-number">2.5</span> Calculate total production and consumption</a></li>
          <li><a href="#summary-data" id="toc-summary-data"><span class="toc-section-number">2.6</span> Summary data</a></li>
          <li><a href="#check-bill-numbers" id="toc-check-bill-numbers"><span class="toc-section-number">2.7</span> Check bill numbers</a></li>
          </ul></li>
          <li><a href="#estimating-the-break-even-point" id="toc-estimating-the-break-even-point"><span class="toc-section-number">3</span> Estimating the break-even point</a></li>
          </ul>
        </nav>
        <ul class="authors">
          <li class="divider"></li>
                                <li><span><i class="glyphicon glyphicon-user"></i> Jason</span></li>
                                         <li><span><i class="glyphicon glyphicon-calendar"></i> 2023-09-12</span></li>
                  </ul>     
      </div>
      <div class="book-body fixed">
        <div class="body-inner">
            <a class="btn pull-left js-toolbar-action toggle-sidebar" aria-label="Toggle Sidebar" title="Toggle Sidebar" href="#">
              <span class="glyphicon glyphicon-menu-hamburger"></span>
            </a>
            <div class="page-inner">
              <section id="content" class="normal">
      
   
        
      <h1 class="title">House solar energy data analysis</h1>
      
        

   
      
   
<!-- Don't indent these lines or it will mess pre blocks indentation --> 
<style type="text/css">
pre, code {white-space:pre !important; overflow-x:auto}
</style>
<p><strong>Disclaimer</strong></p>
<p>All information provided in this website is based on personal experience and data available at the time of posting. Any inaccuracies are solely the responsibility of the author, and readers use the information on this website at their own risk.</p>
<div id="background" class="section level1" number="1">
<h1><span class="header-section-number">1</span> Background</h1>
<p><strong>NOTE</strong> This is a work in progress…</p>
<p>When we were researching solar panels for our house, we found lots of websites describing the general economics of it, such as this helpful <a href="https://ca.renogy.com/blog/what-is-the-average-solar-panels-roi-in-canada/">site</a>, but surprisingly, I could not find any websites/blogs describing real data from a household that had installed solar. What do the grid-energy consumption data look like before and after solar installation? What are the actual hourly / daily patterns of solar energy production and grid energy consumption for a household?</p>
<p>To fill this gap, I’ve decided to share our own data!</p>
<blockquote>
<p>Caveat: we built an addition (short-term rental) at the same time as installing the solar array, therefore these two factors are entirely conflated for my data analyses. In other words, until we get a current metre, I won’t be able to directly compare our electricity consumption (or billing) data from before solar installation with after, because electricity used by the addition will be included.</p>
</blockquote>
<div id="our-household" class="section level2" number="1.1">
<h2><span class="header-section-number">1.1</span> Our household</h2>
<p>We are two adults, two teenagers, and a dog occupying a 1.5 storey, 1260 ft<span class="math inline">\(^{2}\)</span> house in downtown Kelowna, British Columbia. Yeah, it’s a bit tight…</p>
<p>The house was build in the 1940s, so it’s as inefficient as you might expect. For instance, it still has wood chip insulation in most exterior walls. However, with the help of extremely handy members of the extended family, we’ve made some improvements that have definitely improved its efficiency.</p>
<p>We had new roof shingles and a ridge vent installed in December 2020 (leaking forced this), and I subsequently installed proper insulation and venting in the knee-walls next to the dormer bedrooms. That made a huge difference in the dormer rooms… much less hot in the summer, and much warmer in the winter.</p>
<p>In Spring 2022, we added a one-bedroom dwelling (500 ft<span class="math inline">\(^{2}\)</span>) to the west side of the house, and decided this was an opportune time to install solar panels. The addition is very efficient; it has two small heat-pump units, one in the living room and one in the bedroom. It also has an electric fireplace for extra heat when needed (rarely).</p>
<p>Like many folks, we hope to replace our current vehicle with an EV some time in the next four or five years, so having our own energy source would help when the time comes.</p>
<p>We did not buy batteries for storing the solar power. One day maybe…</p>
<p>In November 2022 we replaced the remaining old, large windows on the main floor of our house. The house now feels much more air-tight! That’s the last of the home improvements for a while…</p>
<hr />
</div>
<div id="household-energy-consumption" class="section level2" number="1.2">
<h2><span class="header-section-number">1.2</span> Household energy consumption</h2>
<p>Our typical annual household energy consumption was about 9700 kWh. We’ll show the data for this in a later <a href="#hist_consumption">section</a>.</p>
<p>We heat our house with an efficient gas furnace, so the laundry drier and electric stove/oven are probably the biggest consumers of electricity throughout the year. In the summer, air conditioning draws more. Of course we use A/C mostly when solar production should be greatest…</p>
<hr />
</div>
<div id="the-solar-array" class="section level2" number="1.3">
<h2><span class="header-section-number">1.3</span> The solar array</h2>
<p>In the summer of 2022 we had an array of thirty-six 360W panels (model: Longi LR4-60HPB-360M) installed on our south-facing roof. The entire array size is 12.96kW.</p>
<p>Our solar system was supplied and installed by <a href="https://www.oksolarhomes.com">Okanagan Solar</a>. Their team was amazing to work with.</p>
<p>This system is large for our current needs (about 10,000 kWh / yr), but with the new one-bedroom addition, and hopefully an EV in the next few years, the 12.96kW solar system should be ideal.</p>
<p>The layout of the array on our roof is shown in the following images (provided by Okanagan Solar as part of their assessment):</p>
<p><img src="images/overhead_panels.png" style="width:25.0%" /></p>
<p><img src="images/angle_panels.png" style="width:25.0%" /></p>
<p>Note that the flatter part of the roof extends over our patio.</p>
<p>An added benefit of covering the south-facing roof with solar panels: the kids’ dormer bedrooms are even cooler in the summer, because the panels are intercepting the energy before they hit the roof tiles.</p>
</div>
<div id="installation-cost" class="section level2" number="1.4">
<h2><span class="header-section-number">1.4</span> Installation cost</h2>
<p>The array with installation, including some angled mounting brackets for our flatter roof, cost just under <code>$25K</code>. This does not include the extra electrical upgrades we needed, which we were going to have to do anyways for the addition. These upgrades included a new 200A panel, and a new meter with a new location on our lot. These latter upgrades cost us about <code>$8K</code>, including electricity hookup etc…</p>
<p>OK Solar led us through the Energy Audit process, which ultimately got us the full <code>$5K</code> rebate from the federal green homes initiative, plus the <code>$600</code> for the audit activities themselves.</p>
<p>So, for the solar array installation, the net cost was under <code>$20K</code> after rebates, but not including electrical upgrades.</p>
<hr />
</div>
<div id="electricity-supplier" class="section level2" number="1.5">
<h2><span class="header-section-number">1.5</span> Electricity supplier</h2>
<p>Fortis BC is our electricity provider, and like most places in North America, we don’t have a choice about who we purchase electricity from.</p>
<p>As described at their <a href="https://www.fortisbc.com/about-us/corporate-information/regulatory-affairs/our-electricity-utility/electric-bcuc-submissions/electricity-rates">website</a>, Fortis bills customers bi-monthly, as of 2023, they charge at a fixed rate of <strong>$0.13266</strong>.</p>
<p>Be sure to consult their website to keep track of any updates to rates.</p>
<p><strong>Net metering</strong></p>
<p>Fortis BC has a <a href="https://www.fortisbc.com/services/electricity-services/generating-your-own-electricity/net-metering">net metering program</a>, in which any energy produced by the solar array that is not used immediately on site is put back into the grid, and Fortis keeps track of this and “banks” the kWh on the account. In theory, Fortis then uses these banked amounts against future bills.</p>
<p>Their <a href="https://www.fortisbc.com/services/electricity-services/generating-your-own-electricity/net-metering/understanding-your-net-metering-electricity-bill#item5">website explains what a net-metering bill looks like</a>.</p>
<p>If we happen to have anything left in our “bank” at the end of March, then our account will get credited at a rate equivalent to what Fortis pays their providers. This should be close to $0.10 / kWh.</p>
<hr />
</div>
</div>
<div id="consumption-and-production-data" class="section level1" number="2">
<h1><span class="header-section-number">2</span> Consumption and Production Data</h1>
<p>We officially started producing solar power on July 8, 2022, and net metering started on July 15, 2022. So, between July 8 and July 15, the grid benefited from our solar output!</p>
<div id="solar-energy-production-data" class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> Solar energy production data</h2>
<p>I have another <a href="https://github.com/pitherj/home_solar/blob/main/scripts/wrangle_solar_data.Rmd">script</a> that imports the raw solar energy data files, downloaded from the <a href="https://www.apsystemsema.com">AP Systems website</a>, and wrangles them into an appropriate format.</p>
<p>Here’s what the first few rows of the resulting data table looks like:</p>
<pre><code>## # A tibble: 5,943 × 4
##    date                day         hour    kWh
##    &lt;dttm&gt;              &lt;date&gt;     &lt;dbl&gt;  &lt;dbl&gt;
##  1 2022-07-08 04:00:00 2022-07-08     4  0.002
##  2 2022-07-08 05:00:00 2022-07-08     5  0.02 
##  3 2022-07-08 06:00:00 2022-07-08     6  0.009
##  4 2022-07-08 07:00:00 2022-07-08     7  1.49 
##  5 2022-07-08 08:00:00 2022-07-08     8  1.74 
##  6 2022-07-08 09:00:00 2022-07-08     9  5.65 
##  7 2022-07-08 10:00:00 2022-07-08    10  6.27 
##  8 2022-07-08 11:00:00 2022-07-08    11  9.59 
##  9 2022-07-08 12:00:00 2022-07-08    12 10.8  
## 10 2022-07-08 13:00:00 2022-07-08    13 10.7  
## # ℹ 5,933 more rows</code></pre>
<p>Let’s visualize the data to check for errors:</p>
<div class="figure"><span style="display:block;" id="fig:firstplot"></span>
<img src="index_files/figure-html/firstplot-1.png" alt="Figure 1: Hourly energy output (kWh) for the 36-panel solar array, starting July 8, 2022." width="768" />
<p class="caption">
Figure 2.1: Figure 1: Hourly energy output (kWh) for the 36-panel solar array, starting July 8, 2022.
</p>
</div>
<p>Ah, we see a strange data point… investigating, this is a morning when I took the datalogger offline. The system automatically sums up the total kWh produced over the time period that it was offline.</p>
<pre><code>## # A tibble: 1 × 4
##   date                day         hour   kWh
##   &lt;dttm&gt;              &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt;
## 1 2022-08-30 14:00:00 2022-08-30    14  40.0</code></pre>
<p>So for that day (August 30, 2022), we won’t be able to use the hourly data for analysis.</p>
<p>But we can sum up the total kWh by day, and plot:</p>
<div class="figure"><span style="display:block;" id="fig:secondplot"></span>
<img src="index_files/figure-html/secondplot-1.png" alt="Figure 2: Daily energy output (kWh) for the 36-panel solar array, starting July 8, 2022." width="768" />
<p class="caption">
Figure 2.2: Figure 2: Daily energy output (kWh) for the 36-panel solar array, starting July 8, 2022.
</p>
</div>
<p>And FYI, in 2022 Kelowna got an early start to winter… beginning of November saw more than 30cm of snow fall, and it STAYED! Which meant that the solar panels were covered for the better part of 5 days. I then cleared off a few of them (the steeper angled ones), and we saw a wee bit of sun. However, from November through February each year, Kelowna tends to be very grey… the clouds settle in the valley and just stay here. But it’s often sunny at higher elevation.</p>
<p>The sun started peaking out more in mid-January in the end, so we’ve had more energy production than anticipated!</p>
<hr />
</div>
<div id="grid-energy-consumption-data" class="section level2" number="2.2">
<h2><span class="header-section-number">2.2</span> Grid energy consumption data</h2>
<p>Another <a href="https://github.com/pitherj/home_solar/blob/main/scripts/wrangle_electricity_data.Rmd">script</a> imports the raw Fortis energy consumption data for our account, downloaded from the FortisBC <a href="www.fortisbc.com">website</a>, and wrangles them into an appropriate format.</p>
<p>Annoyingly, these data downloaded from the Fortis portal do not necessarily line up with what Fortis actually uses for billing calculations; this is because they rely on our meter to communicate with them, which doesn’t always happen, in which case they estimate consumption for billing.</p>
<p>I was able to get hourly data going back to January 1, 2019.</p>
<p>Let’s first look at last summer’s data (2022), staring June 1st:</p>
<pre><code>## # A tibble: 40,595 × 4
##    day         hour kw_solar_to_grid kw_fortis_from_grid
##    &lt;date&gt;     &lt;dbl&gt;            &lt;dbl&gt;               &lt;dbl&gt;
##  1 2019-01-01     0               NA               0.915
##  2 2019-01-01     1               NA               0.934
##  3 2019-01-01     2               NA               0.881
##  4 2019-01-01     3               NA               0.927
##  5 2019-01-01     4               NA               0.405
##  6 2019-01-01     5               NA               0.434
##  7 2019-01-01     6               NA               0.576
##  8 2019-01-01     7               NA               0.65 
##  9 2019-01-01     8               NA               0.4  
## 10 2019-01-01     9               NA               0.441
## # ℹ 40,585 more rows</code></pre>
<p>Let’s visualize the data to check for errors, first limiting the date to June 1 2022 and after:</p>
<div class="figure"><span style="display:block;" id="fig:thirdplot"></span>
<img src="index_files/figure-html/thirdplot-1.png" alt="Figure 3: Hourly energy consumption (kWh) for our house, starting June 1, 2022." width="768" />
<p class="caption">
Figure 2.3: Figure 3: Hourly energy consumption (kWh) for our house, starting June 1, 2022.
</p>
</div>
<p>hmm, that’s messy… but it does show that once the solar system was online (July 8), and during daytimes up to the end of October, we typically drew directly from solar, thus zero kWh consumed from the grid.</p>
<p>Let’s sum up the total kWh consumed by day, and visualize:</p>
<div class="figure"><span style="display:block;" id="fig:fourthplot"></span>
<img src="index_files/figure-html/fourthplot-1.png" alt="Figure 4: Daily energy consumption (kWh) for our house, starting June 1, 2022." width="768" />
<p class="caption">
Figure 2.4: Figure 4: Daily energy consumption (kWh) for our house, starting June 1, 2022.
</p>
</div>
<p>Note that the low consumption in June is due to data gaps, which are a mystery to Fortis.</p>
<p>The substantial increase in energy consumption in November was from the combination of early winter/snow/cloud in Kelowna, and 3 weeks with our wonderfully handy in-laws living with us to do final upgrades at our house: replacing 4 windows and a door in the main house. So, over the first 3 weeks of November, we were using more electricity than usual, and we had little sun for solar energy production.</p>
<p>Let’s combine the data into one plot.</p>
<pre><code>## `summarise()` has grouped output by &#39;day&#39;. You can override using the `.groups` argument.</code></pre>
<div class="figure"><span style="display:block;" id="fig:fifthplot"></span>
<img src="index_files/figure-html/fifthplot-1.png" alt="Figure 5: Daily energy consumption (red) and solar production (blue) for our house (kWh), starting June 1, 2022. The solar system came online July 8." width="768" />
<p class="caption">
Figure 2.5: Figure 5: Daily energy consumption (red) and solar production (blue) for our house (kWh), starting June 1, 2022. The solar system came online July 8.
</p>
</div>
<hr />
</div>
<div id="historical-data" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> Historical data</h2>
<p>Let’s have a look at historical data for comparison</p>
<div class="figure"><span style="display:block;" id="fig:histplot"></span>
<img src="index_files/figure-html/histplot-1.png" alt="Figure 6: Daily energy consumption (kWh) for our house, starting January 1, 2019." width="768" />
<p class="caption">
Figure 2.6: Figure 6: Daily energy consumption (kWh) for our house, starting January 1, 2019.
</p>
</div>
<p>Yikes! Despite not being rented out much, the new short-term rental clearly increased our electricity consumption during the cold snap at the end of December 2022, relative to the preceding 3 winters. However, we were still trying to figure out the optimal way to maintain a low temperature (10 degrees) while the suite was unoccupied. The heat pumps work very hard to keep the place warm when it’s -10 or lower outside.</p>
<p>We’ll have to see how we do next winter, and depending on occupancy!</p>
</div>
<div id="average-annual-consumption-hist_consumption." class="section level2" number="2.4">
<h2><span class="header-section-number">2.4</span> Average annual consumption {#hist_consumption}.</h2>
<p>We have historical consumption data dating back to January 1st 2019. So let’s calculate annual consumption for the years since then, using the calendar year as the timeframe:</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-9">Table 2.1: </span>Historical annual (calendar year) electricity consumption.
</caption>
<thead>
<tr>
<th style="text-align:right;">
year
</th>
<th style="text-align:right;">
tot_kWh_used
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
2019
</td>
<td style="text-align:right;">
9112
</td>
</tr>
<tr>
<td style="text-align:right;">
2020
</td>
<td style="text-align:right;">
9776
</td>
</tr>
<tr>
<td style="text-align:right;">
2021
</td>
<td style="text-align:right;">
9826
</td>
</tr>
<tr>
<td style="text-align:right;">
2022
</td>
<td style="text-align:right;">
9742
</td>
</tr>
<tr>
<td style="text-align:right;">
2023
</td>
<td style="text-align:right;">
4954
</td>
</tr>
</tbody>
</table>
<p>Note that the year 2023 is not yet finished, and in 2022 is when we installed the solar.</p>
<p>So, around 9400 kWh was our typical annual electricity consumption, which is a bit lower than average household consumption <a href="https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=2510006201&amp;pickMembers%5B0%5D=1.1&amp;pickMembers%5B1%5D=3.2&amp;cubeTimeFrame.startYear=2017&amp;cubeTimeFrame.endYear=2019&amp;referencePeriods=20170101%2C20190101">across the country</a>.</p>
<p>One important implication of this is that it will take us longer than average to reach the “break even point” on our solar system, simply because we use less electricity annually than a typical household.</p>
<hr />
</div>
<div id="production" class="section level2" number="2.5">
<h2><span class="header-section-number">2.5</span> Calculate total production and consumption</h2>
<p>Let’s do some calculations on the hourly data. Have a look a the data to start, taking a sample of records from July 28th, 2022:</p>
<pre><code>## # A tibble: 16 × 5
##    day         hour kw_solar_to_grid kw_fortis_from_grid kw_solar_gross_produced
##    &lt;date&gt;     &lt;dbl&gt;            &lt;dbl&gt;               &lt;dbl&gt;                   &lt;dbl&gt;
##  1 2022-07-29     6            0.056               0.659                    0.41
##  2 2022-07-29     7            1.01                0.015                    1.63
##  3 2022-07-29     8            1.24                1.24                     3.85
##  4 2022-07-29     9            3.13                0.144                    6.03
##  5 2022-07-29    10            6.70                0                        7.75
##  6 2022-07-29    11            7.95                0                        9.2 
##  7 2022-07-29    12            6.84                0                        8.77
##  8 2022-07-29    13            6.35                0                        9.5 
##  9 2022-07-29    14            5.52                0.007                    8.75
## 10 2022-07-29    15            3.6                 0                        7.67
## 11 2022-07-29    16            2.17                0                        5.36
## 12 2022-07-29    17            0.388               0.813                    2.69
## 13 2022-07-29    18            0.006               1.20                     0.98
## 14 2022-07-29    19            0                   2.28                     0.37
## 15 2022-07-29    20            0                   1.18                     0.09
## 16 2022-07-29    21            0                   2.07                    NA</code></pre>
<p>Aside from the obvious ones (day, hour, date) we have the following fields:</p>
<ul>
<li><code>kw_solar_to_grid</code> is the kWh from our solar system that we fed to the grid (data from Fortis).</li>
<li><code>kw_fortis_from_grid</code> is the kWh that fortis logged as energy provided to us from the grid (data from Fortis).</li>
<li><code>kw_solar_gross_produced</code> is the gross kWh produced by our solar system (data from the system).</li>
</ul>
<p>Focusing on the 14th hour record (2pm), we see that we produced 8.75 kWh of solar energy, and of that, 5.52 went to the grid. However, we also used 0.007 kWh of energy from the grid. This means that at some specific time in that hour we weren’t producing enough solar energy to cover the needs of our house… perhaps a cloud diminished solar production for 10-15 minutes, and during that time we needed to pull power from the grid.</p>
<blockquote>
<p>It’s important to note that the data from the solar array and the data from Fortis may not actually be temporally aligned perfectly. For instance, for the hour between 10am and 11am on a given day, the data associated with the solar array may actually be temporally offset from the data associated with Fortis. This will likely be a source of error / uncertainty.</p>
</blockquote>
<p>Let’s calculate the energy that we consumed directly from our solar, and we’ll call this <code>kw_consumed_from_solar</code>.</p>
<p>This is calculated as the gross solar produced (<code>kw_solar_gross_produced</code>) minus the energy returned to the grid (<code>kw_solar_to_grid</code>).</p>
<p>We’ll then calculate the total energy consumed (<code>tot_kw_consumed</code>), which equals <code>kw_consumed_from_solar</code> plus <code>kw_fortis_from_grid</code>.</p>
<pre><code>## # A tibble: 16 × 8
##    day         hour kw_solar_to_grid kw_fortis_from_grid date                kw_solar_gross_produced kw_consumed_from_solar tot_kw_consumed
##    &lt;date&gt;     &lt;dbl&gt;            &lt;dbl&gt;               &lt;dbl&gt; &lt;dttm&gt;                                &lt;dbl&gt;                  &lt;dbl&gt;           &lt;dbl&gt;
##  1 2022-07-29     6            0.056               0.659 2022-07-29 06:00:00                    0.41                  0.354           1.01 
##  2 2022-07-29     7            1.01                0.015 2022-07-29 07:00:00                    1.63                  0.617           0.632
##  3 2022-07-29     8            1.24                1.24  2022-07-29 08:00:00                    3.85                  2.61            3.85 
##  4 2022-07-29     9            3.13                0.144 2022-07-29 09:00:00                    6.03                  2.9             3.04 
##  5 2022-07-29    10            6.70                0     2022-07-29 10:00:00                    7.75                  1.05            1.05 
##  6 2022-07-29    11            7.95                0     2022-07-29 11:00:00                    9.2                   1.25            1.25 
##  7 2022-07-29    12            6.84                0     2022-07-29 12:00:00                    8.77                  1.93            1.93 
##  8 2022-07-29    13            6.35                0     2022-07-29 13:00:00                    9.5                   3.15            3.15 
##  9 2022-07-29    14            5.52                0.007 2022-07-29 14:00:00                    8.75                  3.23            3.24 
## 10 2022-07-29    15            3.6                 0     2022-07-29 15:00:00                    7.67                  4.07            4.07 
## 11 2022-07-29    16            2.17                0     2022-07-29 16:00:00                    5.36                  3.19            3.19 
## 12 2022-07-29    17            0.388               0.813 2022-07-29 17:00:00                    2.69                  2.30            3.12 
## 13 2022-07-29    18            0.006               1.20  2022-07-29 18:00:00                    0.98                  0.974           2.18 
## 14 2022-07-29    19            0                   2.28  2022-07-29 19:00:00                    0.37                  0.37            2.65 
## 15 2022-07-29    20            0                   1.18  2022-07-29 20:00:00                    0.09                  0.09            1.27 
## 16 2022-07-29    21            0                   2.07  NA                                     0                     0               2.07</code></pre>
<p>Next we’ll calculate some summary statistics…</p>
<hr />
</div>
<div id="summary-data" class="section level2" number="2.6">
<h2><span class="header-section-number">2.6</span> Summary data</h2>
<p>From July 8th to 2023-09-07 (last day of data), let’s calculate how much:</p>
<ul>
<li>total energy consumed from grid (<code>total_kw_fortis_from_grid</code>)</li>
<li>total solar energy returned to grid (<code>total_kw_solar_to_grid</code>)</li>
<li>gross solar energy we’ve produced (<code>total_kw_solar_gross_produced</code>)</li>
<li>solar energy used directly in house (<code>total_kw_solar_used</code>)</li>
<li>total energy consumed (sum of energy from Fortis and from solar) (<code>total_kw_consumed</code>)</li>
</ul>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-14">Table 2.2: </span>Summary of energy production and consumption from July 8 2022 onward.
</caption>
<thead>
<tr>
<th style="text-align:right;">
total_kw_fortis_from_grid
</th>
<th style="text-align:right;">
total_kw_solar_to_grid
</th>
<th style="text-align:right;">
total_kw_solar_gross_produced
</th>
<th style="text-align:right;">
total_kw_solar_used
</th>
<th style="text-align:right;">
total_kw_consumed
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
9786.08
</td>
<td style="text-align:right;">
11971.5
</td>
<td style="text-align:right;">
18881.13
</td>
<td style="text-align:right;">
5048.03
</td>
<td style="text-align:right;">
14834.12
</td>
</tr>
</tbody>
</table>
<p>Do the same for when we started net metering (July 15)</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-15">Table 2.3: </span>Summary of energy production and consumption from July 15 2022 onward.
</caption>
<thead>
<tr>
<th style="text-align:right;">
total_kw_fortis_from_grid
</th>
<th style="text-align:right;">
total_kw_solar_to_grid
</th>
<th style="text-align:right;">
total_kw_solar_gross_produced
</th>
<th style="text-align:right;">
total_kw_solar_used
</th>
<th style="text-align:right;">
total_kw_consumed
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
9705.7
</td>
<td style="text-align:right;">
11971.5
</td>
<td style="text-align:right;">
18337.36
</td>
<td style="text-align:right;">
5048.03
</td>
<td style="text-align:right;">
14753.73
</td>
</tr>
</tbody>
</table>
<p>Now do for one full year of data, July 15 2022 through July 14, 2023 inclusive.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-16">Table 2.4: </span>Summary of energy production and consumption from July 15 2022 to July 14, 2023.
</caption>
<thead>
<tr>
<th style="text-align:right;">
total_kw_fortis_from_grid
</th>
<th style="text-align:right;">
total_kw_solar_to_grid
</th>
<th style="text-align:right;">
total_kw_solar_gross_produced
</th>
<th style="text-align:right;">
total_kw_solar_used
</th>
<th style="text-align:right;">
total_kw_consumed
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
8921.3
</td>
<td style="text-align:right;">
10486.96
</td>
<td style="text-align:right;">
15083.81
</td>
<td style="text-align:right;">
4476.77
</td>
<td style="text-align:right;">
13398.06
</td>
</tr>
</tbody>
</table>
<hr />
</div>
<div id="check-bill-numbers" class="section level2" number="2.7">
<h2><span class="header-section-number">2.7</span> Check bill numbers</h2>
<p>Let’s check the data reported on the bill for July 28th through September 28, 2022.</p>
<p>According to the Fortis bill, we consumed 875 kWh from the grid over that 62 days, and we delivered 2674 kWh back to the grid over that same period.</p>
<p>Using the data downloaded from our solar system and the hourly consumption data downloaded directly from the Fortis website, we get the following numbers:</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-18">Table 2.5: </span>Summary of energy production and consumption from July 29 to Sept 28 2022, inclusive.
</caption>
<thead>
<tr>
<th style="text-align:right;">
total_kw_fortis_from_grid
</th>
<th style="text-align:right;">
total_kw_solar_to_grid
</th>
<th style="text-align:right;">
total_kw_solar_gross_produced
</th>
<th style="text-align:right;">
total_kw_solar_used
</th>
<th style="text-align:right;">
total_kw_consumed
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
871.18
</td>
<td style="text-align:right;">
2653.79
</td>
<td style="text-align:right;">
3498.2
</td>
<td style="text-align:right;">
844.38
</td>
<td style="text-align:right;">
1715.56
</td>
</tr>
</tbody>
</table>
<p>So, a little off, but not too bad.</p>
<p>Now let’s check Sept 29 to Nov 28, which shows 1929 kWh consumed, and 921 kWh returned.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-20">Table 2.6: </span>Summary of energy production and consumption from Sept 29 to Nov 28 2022, inclusive.
</caption>
<thead>
<tr>
<th style="text-align:right;">
total_kw_fortis_from_grid
</th>
<th style="text-align:right;">
total_kw_solar_to_grid
</th>
<th style="text-align:right;">
total_kw_solar_gross_produced
</th>
<th style="text-align:right;">
total_kw_solar_used
</th>
<th style="text-align:right;">
total_kw_consumed
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1954.8
</td>
<td style="text-align:right;">
892.4
</td>
<td style="text-align:right;">
1445.03
</td>
<td style="text-align:right;">
552.62
</td>
<td style="text-align:right;">
2507.42
</td>
</tr>
</tbody>
</table>
<p>A little off again…</p>
<p>Now let’s check Nov 29 to Jan 28, which were extremely cloudy months… it shows 2712 kWh consumed, and 123 kWh returned.</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-22">Table 2.7: </span>Summary of energy production and consumption from Nov 29 2022 to Jan 28 2023, inclusive.
</caption>
<thead>
<tr>
<th style="text-align:right;">
total_kw_fortis_from_grid
</th>
<th style="text-align:right;">
total_kw_solar_to_grid
</th>
<th style="text-align:right;">
total_kw_solar_gross_produced
</th>
<th style="text-align:right;">
total_kw_solar_used
</th>
<th style="text-align:right;">
total_kw_consumed
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
2694
</td>
<td style="text-align:right;">
148.6
</td>
<td style="text-align:right;">
476.78
</td>
<td style="text-align:right;">
328.18
</td>
<td style="text-align:right;">
3022.19
</td>
</tr>
</tbody>
</table>
<p>Still a little off.</p>
<p>A reminder of the amounts for the total period, July 15, 2022 through 2023-09-07 (last day of data):</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-24">Table 2.8: </span>Summary of energy production and consumption from 2022-07-15 to 2023-09-07
</caption>
<thead>
<tr>
<th style="text-align:right;">
total_kw_fortis_from_grid
</th>
<th style="text-align:right;">
total_kw_solar_to_grid
</th>
<th style="text-align:right;">
total_kw_solar_gross_produced
</th>
<th style="text-align:right;">
total_kw_solar_used
</th>
<th style="text-align:right;">
total_kw_consumed
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
9705.7
</td>
<td style="text-align:right;">
11971.5
</td>
<td style="text-align:right;">
18337.36
</td>
<td style="text-align:right;">
5048.03
</td>
<td style="text-align:right;">
14753.73
</td>
</tr>
</tbody>
</table>
<p>That’s pretty amazing… we’re through the most cloudy period of the year (Nov/Dec/Jan), and we produced almost 124% of our energy needs.</p>
<p>Even with the new addition, it seems possible that we’ll produce and bank enough energy (especially in spring/summer) to more than cover our annual needs. However, a key unknown is the added consumption caused by the A/C (heat pumps) in the short-term rental.</p>
<p>Next we’ll figure out money savings.</p>
<hr />
</div>
</div>
<div id="estimating-the-break-even-point" class="section level1" number="3">
<h1><span class="header-section-number">3</span> Estimating the break-even point</h1>
<p>The <strong>break-even point</strong> (BEP) (or “payback period”) is the time it takes for the energy savings to exceed the cost of installation. This <a href="https://www.solar.com/learn/what-is-the-average-payback-period-for-solar-panels/">website</a> provides a useful description.</p>
<p>In its simplified form, BEP is calculated as:</p>
<p>(Initial cost of installation) / (Annual savings)</p>
<p>However, annual savings depends on:</p>
<ul>
<li>the given year’s billing rate, currently (which is likely to increase annually).</li>
<li>any interest paid on loans used to finance the initial installation.</li>
<li>the performance of the solar (e.g. smoky summer skies may decrease savings)</li>
<li>how much electricity one used on average</li>
</ul>
<p>So, for now, we’ll consider the following:</p>
<ul>
<li>initial cost of installation ($20K)</li>
<li>interest rate for financing installation (for us, 3.24%)</li>
<li>estimated savings in first year (as shown below, $1900)</li>
<li>estimated annual inflation in electricity cost (2.5%)</li>
</ul>
<p>I got ChatGPT to write me an R function to calculate BEP, and the function spits out the annual calculations:</p>
<pre><code>payback_period &lt;- function(initial_cost, annual_savings, annual_increase, interest_rate) {
  years &lt;- 0
  annual_results &lt;- data.frame(Year = integer(), Starting_Cost = numeric(), Savings = numeric(), Compound_Interest = numeric(), Ending_Cost = numeric())
  
  while (initial_cost &gt; 0) {
    years &lt;- years + 1
    compound_interest &lt;- initial_cost * interest_rate
    starting_cost &lt;- initial_cost
    savings &lt;- annual_savings
    initial_cost &lt;- initial_cost - annual_savings + compound_interest
    ending_cost &lt;- initial_cost
    annual_savings &lt;- annual_savings * (1 + annual_increase)
    annual_results[years,] &lt;- c(years, starting_cost, savings, compound_interest, ending_cost)
  }
  
  colnames(annual_results) &lt;- c(&quot;Year&quot;, &quot;Starting Cost&quot;, &quot;Savings&quot;, &quot;Compound Interest&quot;, &quot;Ending Cost&quot;)
  
  return(list(years = years, annual_results = annual_results))
}</code></pre>
<p>The arguments for the function:</p>
<ul>
<li>initial_cost: the initial cost of the solar panels installation.<br />
</li>
<li>annual_savings: the amount of money saved in the first year on electricity.<br />
</li>
<li>annual_increase: the annual percentage increase in the cost of electricity.<br />
</li>
<li>interest_rate: the annual interest rate on the financing.</li>
</ul>
<hr />
<p>A few important points to consider prior to estimating our BEP:</p>
<ul>
<li><p>our BEP will be longer than normal, because we added a 500 ft<span class="math inline">\(^{2}\)</span> short-term rental to our house at the same time we added solar. I hope to install a current meter so that we can directly measure energy use in the rental. For now, and based on data so far, I estimate that the short-term rental will increase our annual electricity consumption by around 40%. So, our BEP will be longer because we need to make up for our additional energy demands.</p></li>
<li><p>even though we have high efficiency heat pumps for heating and cooling the rental, the unit consumes more energy than one might expect… probably because when people are on vacation, being energy conscious (like we are in our house) is not top of mind.</p></li>
<li><p>at this early stage we haven’t realized the full benefits of the solar system, because we only started banking kWh on July 15th 2022. I anticipate we’ll bank enough energy in the summer to cover all the winter demand. If so, we’ll be saving about $1900 per year. However, a major source of uncertainty is how much energy the rental unit will use in the summer (due to cooling demands on heat pumps)</p></li>
<li><p>the current billing rate from Fortis is 0.13266 per kWh.</p></li>
</ul>
<hr />
<div id="billing-data" class="section level3" number="3.0.1">
<h3><span class="header-section-number">3.0.1</span> Billing data</h3>
<p>Let’s first see what our bills say so far…</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-27">Table 3.1: </span>Summary of data from bills from July 28 2022 to July 25 2023.
</caption>
<thead>
<tr>
<th style="text-align:left;">
bill_date
</th>
<th style="text-align:right;">
kw_fortis_from_grid
</th>
<th style="text-align:right;">
kw_solar_to_grid
</th>
<th style="text-align:right;">
bank_reading
</th>
<th style="text-align:right;">
meter_reading
</th>
<th style="text-align:right;">
rate
</th>
<th style="text-align:right;">
paid
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
2022-07-28
</td>
<td style="text-align:right;">
1380
</td>
<td style="text-align:right;">
1183
</td>
<td style="text-align:right;">
1183
</td>
<td style="text-align:right;">
69883
</td>
<td style="text-align:right;">
0.12
</td>
<td style="text-align:right;">
24.36
</td>
</tr>
<tr>
<td style="text-align:left;">
2022-09-28
</td>
<td style="text-align:right;">
875
</td>
<td style="text-align:right;">
2674
</td>
<td style="text-align:right;">
3857
</td>
<td style="text-align:right;">
70758
</td>
<td style="text-align:right;">
0.12
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
2022-11-28
</td>
<td style="text-align:right;">
1929
</td>
<td style="text-align:right;">
921
</td>
<td style="text-align:right;">
4778
</td>
<td style="text-align:right;">
72687
</td>
<td style="text-align:right;">
0.12
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
2023-01-28
</td>
<td style="text-align:right;">
2712
</td>
<td style="text-align:right;">
123
</td>
<td style="text-align:right;">
4901
</td>
<td style="text-align:right;">
75399
</td>
<td style="text-align:right;">
0.13
</td>
<td style="text-align:right;">
231.20
</td>
</tr>
<tr>
<td style="text-align:left;">
2023-04-05
</td>
<td style="text-align:right;">
1928
</td>
<td style="text-align:right;">
1397
</td>
<td style="text-align:right;">
6298
</td>
<td style="text-align:right;">
77327
</td>
<td style="text-align:right;">
0.13
</td>
<td style="text-align:right;">
70.44
</td>
</tr>
<tr>
<td style="text-align:left;">
2023-05-25
</td>
<td style="text-align:right;">
713
</td>
<td style="text-align:right;">
2120
</td>
<td style="text-align:right;">
8418
</td>
<td style="text-align:right;">
78040
</td>
<td style="text-align:right;">
0.13
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
<tr>
<td style="text-align:left;">
2023-07-25
</td>
<td style="text-align:right;">
764
</td>
<td style="text-align:right;">
2776
</td>
<td style="text-align:right;">
11194
</td>
<td style="text-align:right;">
78804
</td>
<td style="text-align:right;">
0.13
</td>
<td style="text-align:right;">
0.00
</td>
</tr>
</tbody>
</table>
<p>We can calculate what the cost would have been “real_cost” and what our savings were based on what we actually paid:</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-29">Table 3.2: </span>Summary of data from bills from July 28 2022 to uly 25 2023.
</caption>
<thead>
<tr>
<th style="text-align:left;">
bill_date
</th>
<th style="text-align:right;">
kw_fortis_from_grid
</th>
<th style="text-align:right;">
kw_solar_to_grid
</th>
<th style="text-align:right;">
bank_reading
</th>
<th style="text-align:right;">
meter_reading
</th>
<th style="text-align:right;">
rate
</th>
<th style="text-align:right;">
real_cost
</th>
<th style="text-align:right;">
paid
</th>
<th style="text-align:right;">
saving
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
2022-07-28
</td>
<td style="text-align:right;">
1380
</td>
<td style="text-align:right;">
1183
</td>
<td style="text-align:right;">
1183
</td>
<td style="text-align:right;">
69883
</td>
<td style="text-align:right;">
0.12
</td>
<td style="text-align:right;">
170.64
</td>
<td style="text-align:right;">
24.36
</td>
<td style="text-align:right;">
146.28
</td>
</tr>
<tr>
<td style="text-align:left;">
2022-09-28
</td>
<td style="text-align:right;">
875
</td>
<td style="text-align:right;">
2674
</td>
<td style="text-align:right;">
3857
</td>
<td style="text-align:right;">
70758
</td>
<td style="text-align:right;">
0.12
</td>
<td style="text-align:right;">
108.19
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
108.19
</td>
</tr>
<tr>
<td style="text-align:left;">
2022-11-28
</td>
<td style="text-align:right;">
1929
</td>
<td style="text-align:right;">
921
</td>
<td style="text-align:right;">
4778
</td>
<td style="text-align:right;">
72687
</td>
<td style="text-align:right;">
0.12
</td>
<td style="text-align:right;">
238.52
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
238.52
</td>
</tr>
<tr>
<td style="text-align:left;">
2023-01-28
</td>
<td style="text-align:right;">
2712
</td>
<td style="text-align:right;">
123
</td>
<td style="text-align:right;">
4901
</td>
<td style="text-align:right;">
75399
</td>
<td style="text-align:right;">
0.13
</td>
<td style="text-align:right;">
357.98
</td>
<td style="text-align:right;">
231.20
</td>
<td style="text-align:right;">
126.78
</td>
</tr>
<tr>
<td style="text-align:left;">
2023-04-05
</td>
<td style="text-align:right;">
1928
</td>
<td style="text-align:right;">
1397
</td>
<td style="text-align:right;">
6298
</td>
<td style="text-align:right;">
77327
</td>
<td style="text-align:right;">
0.13
</td>
<td style="text-align:right;">
255.65
</td>
<td style="text-align:right;">
70.44
</td>
<td style="text-align:right;">
185.21
</td>
</tr>
<tr>
<td style="text-align:left;">
2023-05-25
</td>
<td style="text-align:right;">
713
</td>
<td style="text-align:right;">
2120
</td>
<td style="text-align:right;">
8418
</td>
<td style="text-align:right;">
78040
</td>
<td style="text-align:right;">
0.13
</td>
<td style="text-align:right;">
94.54
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
94.54
</td>
</tr>
<tr>
<td style="text-align:left;">
2023-07-25
</td>
<td style="text-align:right;">
764
</td>
<td style="text-align:right;">
2776
</td>
<td style="text-align:right;">
11194
</td>
<td style="text-align:right;">
78804
</td>
<td style="text-align:right;">
0.13
</td>
<td style="text-align:right;">
101.31
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
101.31
</td>
</tr>
</tbody>
</table>
<p>So, based on billing numbers, the amount we would have had to pay since July 2022 is $1326.84, what we actually paid was $326, and our savings were $1000.84. That’s a 75% saving.</p>
<p>That’s not bad, but not as good as it will be!</p>
<hr />
</div>
<div id="calculate-bep" class="section level3" number="3.0.2">
<h3><span class="header-section-number">3.0.2</span> Calculate BEP</h3>
<p>Now we’ll use our function to estimate the BEP.</p>
<p>To reiterate, we don’t yet have a years’ worth of data to accurately estimate the initial year of savings. AND, we’re using around 40% more electricity than we did before installing solar (due to short term rental)…</p>
<p>So, we’ll explore a few scenarios, all of which assume an inflation rate of 2.5% (this can be varied also…), use the financing interest rate of 3.24%, and initial installation cost of $20K.</p>
<p>We assume that there’s no banked kWh left for payback at the end of the year.</p>
<ol style="list-style-type: decimal">
<li><p>Assume we produce enough solar to cover annual needs; At the current billing rate of $0.13266/kWh, and estimating we’ll consume 14mWh, this translates to $1857.24 / yr savings.</p></li>
<li><p>Assume we cover 80% of needs, which results in $1485.79 savings</p></li>
<li><p>Assume we cover 70% of needs, which results in $1300.07 savings.</p></li>
</ol>
<p>Here we go:</p>
<p><img src="index_files/figure-html/unnamed-chunk-31-1.png" width="768" /></p>
<p>So for now, the optimistic estimate for BEP is just under 12 years.</p>
<p>The estimates for the BEP if we didn’t have the short-term rental (a more reasonable scenario for most folks) require a bit more work…</p>
<p>Stay tuned - I’ll update these numbers as we get more data!</p>
</div>
</div>

   
   
           </section>
  </div>
  </div>
  </div>
  </div>
      
      

  <script>
    $(document).ready(function () {

		// add bootstrap table styles to pandoc tables
	$('tr.header').parent('thead').parent('table').addClass('table table-condensed');
		
 		
	    });
  </script>



    <!-- dynamically load mathjax for compatibility with self-contained -->
  <script>
    (function () {
	var script = document.createElement("script");
	script.type = "text/javascript";
	script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
	document.getElementsByTagName("head")[0].appendChild(script);
    })();
  </script>
  
</body>
</html>
